apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  labels: #We use this to group or tag the object
    app: my-app
    version: 1.0.0-Snapshot
    env: dev

spec:
  containers: #Array or list
    - name: nginx-container
      image: nginx
      # image: nginx:alpine

    # You can have multiple containers in the same pod
    # - name: back-end-container
    #   image: back-end-app
