apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app-rc
  labels:
    app: my-app-rc
    version: 1.0.0-Snapshot
    env: dev

spec:
  template: #We put the pod we want to replicate
    metadata:
      name: my-app-pod
      labels:
        app: my-app
        version: 1.0.0-Snapshot
        env: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2
