apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: dev      # This will always create the quota inside the namespace dev

spec:
    hard:
      pods: "10"
      request.cpu: "4"
      request.memory: 5Gi
      limit.cpu: "10"
      limit.memory: 10Gi
