apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    # To manually import each secret
    env:
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-host
          key: DB_HOST
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: DB_USER
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: DB_PASSWORD

    # To import every secret
    # envFrom:
      # - secretRef:
          # name: db-credentials

    # To mount secrets as volumes, this creates a file with the value of the secret as content
    # "inside container" -- cat /ot/app-secret-volume/DB_HOST    --cat output: mysql
    # volumes:
    # - name: app-secret-volume
    #   secret:
    #     secretname: db-credentials
    ports:
    - containerPort: 80
