apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  # this will mount the dashboard-sa SA in the pod --- /var/run/secrets/kubernetes.io/serviceaccount/
  serviceAccountName: dashboard-sa
  # If you don't want to mount the SA
  # automountServiceAccountToken: false
  containers:
  - name: ubuntu
    image: ubuntu
