apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  # By default, each pod failure is counted towards the backOff
  # use backoffLimit to specify the number of retries before considering a Job as failed.
  backoffLimit: 0
  # How many times to run this job (here it will create 2 pods one after each other)
  # if one pod fails it will create another pod until it has 2 successes
  completions: 2
  # To run multiple pods in parallel
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: math-add
          image: ubuntu
          command:
            - "expr"
            - "3"
            - "+"
            - "2"

# To see response use
# kubectl logs math-add-job-ld87pn
