apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  # Use to make a pod accesible on a port of the nodes ip
  type: NodePort
  # This connects the service to a pod using the (01-basic-pod.yaml) Labels
  # If you have multiple pods with this labels k8s will map them all and when a request arrives it randomly
  #   selects one to send the traffic, so it acts kind of like a load balancer but randomly
  selector:
    app: my-app
    version: 1.0.0-Snapshot
    env: dev
  ports:
    - port: 80
      # Optional field: By default the `targetPort` is set to the same value as the `port` field.
      targetPort: 80
      # Optional field: By default the Kubernetes control plane will allocate a random port from a range (default: 30000-32767)
      # This is the port we'll use externally to access the app
      nodePort: 30007
