# kubectl config my-context   # set context to my-context
# kubectl config view         # get current context

current-context: my-context
apiVersion: v1
kind: Config

clusters:
- name: development-cluster
  cluster:
    certificate-authority: /path/to/my/ca.crt # CERTIFICATE AUTHORITY THAT ISSUED YOUR TLS CERT
    server: https://horse.org:4443 # this name needs to be on the certificate in --tls-cert-file
    # proxy-url: http://proxy.example.org:3128

users:
- name: developer
  user:
    client-certificate: path/to/my/client/cert # we'll get to this later
    client-key: path/to/my/client/key # we'll get to this later

contexts:
- name: development
  context:
    cluster: development-cluster
    user: developer
    namespace: dev-ns
