# ClusterRole, by contrast, is a non-namespaced resource.
# The resources have different names (Role and ClusterRole) because a Kubernetes object
#   always has to be either namespaced or not namespaced; it can't be both.

# ClusterRoles are cluster-scoped

# If you want to define a role within a namespace, use a Role; if you want to define a role cluster-wide, use a ClusterRole.

# grant read access to secrets in any particular namespace, or across all namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: secret-reader
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
