# Admission webhooks are HTTP callbacks that receive admission requests and do something with them.
# You can define two types of admission webhooks, validating admission webhook and mutating admission webhook.
# Mutating admission webhooks are invoked first, and can modify objects sent to the API server to enforce custom defaults.
# After all object modifications are complete, and after the incoming object is validated by the API server,
# validating admission webhooks are invoked and can reject requests to enforce custom policies.

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "cool-pod-policy.example.com"
webhooks:
- name: "cool-pod-policy.example.com"
  # When to call the server, in the example we only call this webhook when there are calls to create pods
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  # Location of the Admission webhook
  clientConfig:
    service:
      namespace: "cool-namespace"
      name: "cool-service"
    caBundle: <CA_BUNDLE>
    # Example of an external url
    # url: "http://external-server.example.com"
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
