#Create a pod with the ubuntu image to run a container to sleep for 5000 seconds.
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-2
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args: ["5000"]

#Create a pod using the file named ubuntu-sleeper-3.yaml. There is something wrong with it. Try to fix it!
#Criteria: ---Pod Name: ubuntu-sleeper-3      ---Command: sleep 1200
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-3
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command:
      - "sleep"
      - "1200"

# Inspect the file Dockerfile given at /root/webapp-color directory. What command is run at container startup?
# Dockerfile
FROM python:3.6-alpine
RUN pip install flask
COPY . /opt/
EXPOSE 8080
WORKDIR /opt
ENTRYPOINT ["python", "app.py"]
# python app.py

# Inspect the file Dockerfile2 given at /root/webapp-color directory. What command is run at container startup?
# Dockerfile2
FROM python:3.6-alpine
RUN pip install flask
COPY . /opt/
EXPOSE 8080
WORKDIR /opt
ENTRYPOINT ["python", "app.py"]
CMD ["--color", "red"]
# python app.py --color red

# Inspect the file given at /root/webapp-color-pod-2.yaml directory. What command is run at container startup?
# webapp-color-pod-2.yaml
apiVersion: v1
kind: Pod
metadata:
  name: webapp-green
  labels:
      name: webapp-green
spec:
  containers:
  - name: simple-webapp
    image: kodekloud/webapp-color
    command: ["python", "app.py"]
    args: ["--color", "pink"]
# python app.py --color pink
